name: Windows EXE Build

on:
  push:
    branches: [ master, main ]
    tags: [ 'v*' ]
  workflow_dispatch: {}

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Install UPX
        run: |
          choco install upx -y

      - name: Build EXE with PyInstaller (spec)
        env:
          UPX_DIR: C:\\ProgramData\\chocolatey\\lib\\upx\\tools
        run: |
          pyinstaller --noconfirm --clean pyinstaller.spec --upx-dir "%UPX_DIR%"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GridImgViewer-windows
          path: dist/GridImgViewer.exe
          if-no-files-found: error

      - name: Release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/GridImgViewer.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


